export type DemoTone = 'good' | 'warn' | 'critical' | 'info'

export type VendorCase = {
  vendorId: number
  mainChefId: number
  city: string
  cuisine: string
  storyTag: string
  classification: 'Healthy' | 'High Potential' | 'At Risk' | 'Needs Attention'
  finalScore: number
  summary: string
  reason: string
  actionHint: string
  kpis: {
    deliveredOrdersRecent: number
    deliveredOrdersPrev: number
    ordersTrendPct: number
    deliveredGmvRecent: number
    deliveredGmvPrev: number
    gmvTrendPct: number
    avgOrderValueRecent: number
    deliveredRateRecent: number
    declineRateRecent: number
    cancelRateRecent: number
    freeDeliveryRateRecent: number
    subsidyRatioRecent: number
    netTakeRatioRecent: number
  }
  scores: {
    growth: number
    quality: number
    efficiency: number
    seasonality: number
    benchmark: number
  }
  benchmarks: {
    ordersPercentile: number
    gmvPercentile: number
    aovPercentile: number
    qualityPercentile: number
    efficiencyPercentile: number
  }
  copilot: {
    performanceSummary: string
    likelyCauses: string[]
    actions: string[]
    talkingPoints: string[]
    watchout: string
  }
}

export const vendorCases: VendorCase[] = [
  {
    vendorId: 100000,
    mainChefId: 1000,
    city: 'Riyadh',
    cuisine: 'Groceries',
    storyTag: 'ramadan_star',
    classification: 'Healthy',
    finalScore: 87.57,
    summary: 'Strong growth, strong quality, and efficient support profile.',
    reason: 'positive recent growth; strong delivery quality; healthy subsidy efficiency',
    actionHint: 'Maintain momentum: protect service quality, keep efficient support, and test small growth levers.',
    kpis: {
      deliveredOrdersRecent: 298,
      deliveredOrdersPrev: 231,
      ordersTrendPct: 29.21,
      deliveredGmvRecent: 34567.42,
      deliveredGmvPrev: 26181.12,
      gmvTrendPct: 32.03,
      avgOrderValueRecent: 116.0,
      deliveredRateRecent: 0.935,
      declineRateRecent: 0.028,
      cancelRateRecent: 0.0366,
      freeDeliveryRateRecent: 0.0976,
      subsidyRatioRecent: 0.0059,
      netTakeRatioRecent: 0.1695,
    },
    scores: {
      growth: 92,
      quality: 82,
      efficiency: 94,
      seasonality: 86,
      benchmark: 84,
    },
    benchmarks: {
      ordersPercentile: 88,
      gmvPercentile: 91,
      aovPercentile: 77,
      qualityPercentile: 81,
      efficiencyPercentile: 93,
    },
    copilot: {
      performanceSummary: 'This vendor is performing strongly across growth, quality, and commercial efficiency. Orders and GMV are growing well, delivery quality is healthy, and the branch appears to be converting seasonal demand effectively.',
      likelyCauses: [
        'Strong fit between the vendor operating model and customer demand patterns.',
        'Good execution during high-demand periods, especially Ramadan-relevant demand windows.',
        'Commercial support appears controlled rather than overly dependent on subsidy.',
      ],
      actions: [
        'Protect service quality while scaling demand during strong dayparts.',
        'Identify the best-performing SKUs and make them more visible during peak windows.',
        'Run a light growth test without materially increasing subsidy exposure.',
      ],
      talkingPoints: [
        'Your branch is showing healthy growth and strong operational consistency.',
        'We want to preserve quality while scaling the strongest demand windows.',
        'We recommend focused visibility and assortment optimization rather than aggressive discounting.',
      ],
      watchout: 'Avoid over-scaling promotions in a way that weakens the current healthy efficiency profile.',
    },
  },
  {
    vendorId: 100010,
    mainChefId: 1000,
    city: 'Riyadh',
    cuisine: 'Groceries',
    storyTag: 'iftar_builder',
    classification: 'High Potential',
    finalScore: 81.42,
    summary: 'Healthy quality with room to scale branch demand more aggressively.',
    reason: 'good quality but branch still under-scaled versus peer demand',
    actionHint: 'Push visibility in strong meal windows and scale winning assortments carefully.',
    kpis: {
      deliveredOrdersRecent: 214,
      deliveredOrdersPrev: 181,
      ordersTrendPct: 18.23,
      deliveredGmvRecent: 24890.54,
      deliveredGmvPrev: 21420.16,
      gmvTrendPct: 16.2,
      avgOrderValueRecent: 116.31,
      deliveredRateRecent: 0.929,
      declineRateRecent: 0.024,
      cancelRateRecent: 0.046,
      freeDeliveryRateRecent: 0.091,
      subsidyRatioRecent: 0.0098,
      netTakeRatioRecent: 0.1687,
    },
    scores: {
      growth: 82,
      quality: 80,
      efficiency: 85,
      seasonality: 89,
      benchmark: 71,
    },
    benchmarks: {
      ordersPercentile: 57,
      gmvPercentile: 61,
      aovPercentile: 76,
      qualityPercentile: 79,
      efficiencyPercentile: 84,
    },
    copilot: {
      performanceSummary: 'This branch has healthy operating quality and stable commercial performance, but still has headroom to scale relative to nearby peers.',
      likelyCauses: [
        'Execution is good enough to support more traffic.',
        'Demand opportunity appears under-captured during strong meal windows.',
        'The branch likely needs sharper exposure rather than deeper discounting.',
      ],
      actions: [
        'Increase placement during the best converting windows.',
        'Promote high-repeat items instead of broad offers.',
        'Monitor cancel and decline rates while traffic scales.',
      ],
      talkingPoints: [
        'This branch looks operationally ready for more demand.',
        'We want to scale intelligently, not just spend more on support.',
        'The biggest upside is stronger visibility on proven items.',
      ],
      watchout: 'Do not add traffic faster than the branch can absorb during peak meal windows.',
    },
  },
  {
    vendorId: 100018,
    mainChefId: 1000,
    city: 'Riyadh',
    cuisine: 'Groceries',
    storyTag: 'support_leak',
    classification: 'Needs Attention',
    finalScore: 69.28,
    summary: 'Demand is acceptable, but efficiency is slipping because support is doing too much work.',
    reason: 'high free delivery and subsidy support for only moderate branch growth',
    actionHint: 'Tighten support strategy and see which demand holds organically.',
    kpis: {
      deliveredOrdersRecent: 176,
      deliveredOrdersPrev: 161,
      ordersTrendPct: 9.32,
      deliveredGmvRecent: 19341.18,
      deliveredGmvPrev: 18127.64,
      gmvTrendPct: 6.69,
      avgOrderValueRecent: 109.89,
      deliveredRateRecent: 0.903,
      declineRateRecent: 0.029,
      cancelRateRecent: 0.068,
      freeDeliveryRateRecent: 0.187,
      subsidyRatioRecent: 0.0271,
      netTakeRatioRecent: 0.1641,
    },
    scores: {
      growth: 65,
      quality: 70,
      efficiency: 52,
      seasonality: 74,
      benchmark: 63,
    },
    benchmarks: {
      ordersPercentile: 49,
      gmvPercentile: 51,
      aovPercentile: 69,
      qualityPercentile: 67,
      efficiencyPercentile: 42,
    },
    copilot: {
      performanceSummary: 'This branch is not in immediate danger, but the efficiency picture is weakening because commercial support looks heavier than the growth it is producing.',
      likelyCauses: [
        'Free delivery and subsidy may be overused relative to branch performance.',
        'Some of the observed demand may be support-led rather than organic.',
        'The branch likely needs a more targeted promotion setup.',
      ],
      actions: [
        'Reduce broad support and test selective promo windows.',
        'Review whether the highest-supported baskets are actually incremental.',
        'Track order retention after support is tightened.',
      ],
      talkingPoints: [
        'The branch is stable, but support may be eating too much efficiency.',
        'We want to preserve demand while making the spend more targeted.',
        'The goal is better quality growth, not just more subsidized volume.',
      ],
      watchout: 'If support is removed too aggressively, short-term performance could swing sharply.',
    },
  },
  {
    vendorId: 100078,
    mainChefId: 1019,
    city: 'Jeddah',
    cuisine: 'Groceries',
    storyTag: 'late_night_hero',
    classification: 'High Potential',
    finalScore: 79.34,
    summary: 'Strong operational quality and strong Ramadan late-night fit, with more room to scale.',
    reason: 'good quality but below-median scale in cuisine; strong Ramadan late-night fit; efficient commercial profile',
    actionHint: 'Scale selectively: increase visibility, extend strong dayparts, and support winning SKUs without over-subsidizing.',
    kpis: {
      deliveredOrdersRecent: 230,
      deliveredOrdersPrev: 192,
      ordersTrendPct: 19.79,
      deliveredGmvRecent: 24500.12,
      deliveredGmvPrev: 20887.31,
      gmvTrendPct: 17.3,
      avgOrderValueRecent: 106.52,
      deliveredRateRecent: 0.9274,
      declineRateRecent: 0.0242,
      cancelRateRecent: 0.0484,
      freeDeliveryRateRecent: 0.0887,
      subsidyRatioRecent: 0.011,
      netTakeRatioRecent: 0.169,
    },
    scores: {
      growth: 81,
      quality: 78,
      efficiency: 84,
      seasonality: 98.95,
      benchmark: 73,
    },
    benchmarks: {
      ordersPercentile: 45,
      gmvPercentile: 48,
      aovPercentile: 58,
      qualityPercentile: 77,
      efficiencyPercentile: 74,
    },
    copilot: {
      performanceSummary: 'This branch is a strong growth opportunity. Quality is solid, commercial efficiency is healthy, and the vendor shows strong Ramadan late-night fit, but it is still not fully scaled relative to peer potential.',
      likelyCauses: [
        'Operational fundamentals are strong enough to support more demand.',
        'Seasonal and late-night demand patterns suggest underused upside.',
        'The branch likely has room to grow through visibility and timing rather than heavy subsidy.',
      ],
      actions: [
        'Increase visibility during high-conversion evening and Ramadan-relevant time windows.',
        'Promote the strongest baskets or hero items rather than broad discounts.',
        'Test controlled traffic growth while monitoring cancel and decline rates.',
      ],
      talkingPoints: [
        'Your branch is performing well operationally and has room to grow further.',
        'We see strong demand potential in late-night and Ramadan-relevant windows.',
        'We want to scale efficiently by focusing on timing, visibility, and winning products.',
      ],
      watchout: 'Do not scale demand too aggressively without watching service quality during peak periods.',
    },
  },
  {
    vendorId: 100081,
    mainChefId: 1019,
    city: 'Jeddah',
    cuisine: 'Groceries',
    storyTag: 'steady_nights',
    classification: 'Healthy',
    finalScore: 76.11,
    summary: 'Balanced branch with reliable quality and consistent night-time demand execution.',
    reason: 'healthy branch-level growth with stable operating quality',
    actionHint: 'Protect consistency and replicate the best-performing night-time baskets.',
    kpis: {
      deliveredOrdersRecent: 188,
      deliveredOrdersPrev: 163,
      ordersTrendPct: 15.34,
      deliveredGmvRecent: 20562.44,
      deliveredGmvPrev: 18351.27,
      gmvTrendPct: 12.05,
      avgOrderValueRecent: 109.37,
      deliveredRateRecent: 0.9341,
      declineRateRecent: 0.0218,
      cancelRateRecent: 0.0431,
      freeDeliveryRateRecent: 0.0812,
      subsidyRatioRecent: 0.0089,
      netTakeRatioRecent: 0.1699,
    },
    scores: {
      growth: 76,
      quality: 83,
      efficiency: 86,
      seasonality: 87,
      benchmark: 71,
    },
    benchmarks: {
      ordersPercentile: 52,
      gmvPercentile: 56,
      aovPercentile: 61,
      qualityPercentile: 82,
      efficiencyPercentile: 79,
    },
    copilot: {
      performanceSummary: 'This branch is not the breakout growth story in the portfolio, but it is a dependable performer with healthy service quality and commercially disciplined growth.',
      likelyCauses: [
        'Good operating consistency is keeping service quality stable.',
        'Demand looks repeatable rather than heavily promotion-driven.',
        'The branch benefits from dependable night-time demand behavior.',
      ],
      actions: [
        'Replicate top-performing basket combinations more intentionally.',
        'Protect quality during the busiest late-night windows.',
        'Test small visibility improvements before changing support strategy.',
      ],
      talkingPoints: [
        'This branch is performing from a stable operational base.',
        'The opportunity is to scale what already works, not to reset the model.',
        'We should protect service quality while building on repeatable demand.',
      ],
      watchout: 'A stable branch can lose momentum if it is ignored in favor of louder high-growth cases.',
    },
  },
  {
    vendorId: 100089,
    mainChefId: 1019,
    city: 'Jeddah',
    cuisine: 'Groceries',
    storyTag: 'peak_strain',
    classification: 'At Risk',
    finalScore: 68.47,
    summary: 'Demand is there, but quality is breaking during peak windows and needs intervention.',
    reason: 'branch growth is being undermined by elevated cancellations and weaker delivery quality',
    actionHint: 'Stabilize branch operations first, then resume scaling.',
    kpis: {
      deliveredOrdersRecent: 201,
      deliveredOrdersPrev: 176,
      ordersTrendPct: 14.2,
      deliveredGmvRecent: 21317.9,
      deliveredGmvPrev: 19401.3,
      gmvTrendPct: 9.88,
      avgOrderValueRecent: 106.06,
      deliveredRateRecent: 0.884,
      declineRateRecent: 0.031,
      cancelRateRecent: 0.094,
      freeDeliveryRateRecent: 0.102,
      subsidyRatioRecent: 0.0147,
      netTakeRatioRecent: 0.1663,
    },
    scores: {
      growth: 72,
      quality: 55,
      efficiency: 74,
      seasonality: 90,
      benchmark: 63,
    },
    benchmarks: {
      ordersPercentile: 54,
      gmvPercentile: 57,
      aovPercentile: 57,
      qualityPercentile: 41,
      efficiencyPercentile: 66,
    },
    copilot: {
      performanceSummary: 'This branch has enough demand to grow, but the quality profile is deteriorating. Peak strain is now visible in the cancellation and delivered-rate pattern.',
      likelyCauses: [
        'Operational capacity may not be keeping up with demand peaks.',
        'Late-night or weekend surges are likely amplifying fulfillment issues.',
        'The branch may be scaling demand faster than service quality can support.',
      ],
      actions: [
        'Investigate the operational source of cancellations immediately.',
        'Hold back on traffic expansion until service quality stabilizes.',
        'Review whether menu complexity or staffing is driving the peak issue.',
      ],
      talkingPoints: [
        'Demand is healthy, but service quality is now the real constraint.',
        'We need to fix the branch operating issue before adding more traffic.',
        'Protecting customer experience will preserve growth better than more support.',
      ],
      watchout: 'If the branch keeps scaling without fixing cancellations, repeat demand could deteriorate.',
    },
  },
  {
    vendorId: 100223,
    mainChefId: 1094,
    city: 'Jeddah',
    cuisine: 'Flowers & Gifts',
    storyTag: 'steady_builder',
    classification: 'Healthy',
    finalScore: 84.26,
    summary: 'Excellent quality and strong growth in a non-core vertical, proving cross-category value.',
    reason: 'positive recent growth; strong delivery quality; healthy subsidy efficiency',
    actionHint: 'Maintain momentum: protect service quality, keep efficient support, and test small growth levers.',
    kpis: {
      deliveredOrdersRecent: 91,
      deliveredOrdersPrev: 55,
      ordersTrendPct: 65.45,
      deliveredGmvRecent: 14632.2,
      deliveredGmvPrev: 9444.8,
      gmvTrendPct: 54.93,
      avgOrderValueRecent: 160.79,
      deliveredRateRecent: 0.9579,
      declineRateRecent: 0.0316,
      cancelRateRecent: 0.0105,
      freeDeliveryRateRecent: 0.0737,
      subsidyRatioRecent: 0.0042,
      netTakeRatioRecent: 0.1701,
    },
    scores: {
      growth: 97,
      quality: 92,
      efficiency: 95,
      seasonality: 71,
      benchmark: 76,
    },
    benchmarks: {
      ordersPercentile: 63,
      gmvPercentile: 74,
      aovPercentile: 89,
      qualityPercentile: 95,
      efficiencyPercentile: 92,
    },
    copilot: {
      performanceSummary: 'This vendor is a strong operator in a different vertical, which shows the copilot works beyond core restaurant cases. Growth is strong, quality is excellent, and the branch appears commercially disciplined.',
      likelyCauses: [
        'Strong merchant execution and reliability.',
        'Good fit between product offering and customer need in its category.',
        'Demand growth is happening without excessive subsidy dependence.',
      ],
      actions: [
        'Preserve the current service model that is driving reliable performance.',
        'Test one targeted growth lever, such as placement or category visibility.',
        'Review top-performing periods and replicate that demand pattern more consistently.',
      ],
      talkingPoints: [
        'Your branch is operating from a strong position and growing efficiently.',
        'We recommend measured expansion, not a major reset.',
        'The focus should be on replicating what already works best.',
      ],
      watchout: 'Small quality slips could become more visible if growth accelerates quickly.',
    },
  },
  {
    vendorId: 100231,
    mainChefId: 1094,
    city: 'Riyadh',
    cuisine: 'Flowers & Gifts',
    storyTag: 'gift_peak',
    classification: 'High Potential',
    finalScore: 78.63,
    summary: 'Great category fit and high basket value, but branch demand still has upside.',
    reason: 'good quality and high AOV, but branch demand remains below potential',
    actionHint: 'Improve category visibility around gifting moments and keep execution tight.',
    kpis: {
      deliveredOrdersRecent: 74,
      deliveredOrdersPrev: 58,
      ordersTrendPct: 27.59,
      deliveredGmvRecent: 12671.8,
      deliveredGmvPrev: 10110.5,
      gmvTrendPct: 25.33,
      avgOrderValueRecent: 171.24,
      deliveredRateRecent: 0.948,
      declineRateRecent: 0.028,
      cancelRateRecent: 0.018,
      freeDeliveryRateRecent: 0.067,
      subsidyRatioRecent: 0.0057,
      netTakeRatioRecent: 0.1704,
    },
    scores: {
      growth: 84,
      quality: 90,
      efficiency: 89,
      seasonality: 74,
      benchmark: 68,
    },
    benchmarks: {
      ordersPercentile: 54,
      gmvPercentile: 66,
      aovPercentile: 93,
      qualityPercentile: 92,
      efficiencyPercentile: 88,
    },
    copilot: {
      performanceSummary: 'This branch combines healthy quality with very strong basket value, but the overall branch scale is still below what the category and operating quality could support.',
      likelyCauses: [
        'The branch likely has room to win more demand during gifting-led occasions.',
        'High AOV suggests customers value the assortment when they do convert.',
        'The branch may need stronger positioning rather than commercial support.',
      ],
      actions: [
        'Increase visibility around gifting and occasion-driven demand moments.',
        'Promote high-conversion bundles that preserve AOV strength.',
        'Track whether stronger visibility translates into repeat order growth.',
      ],
      talkingPoints: [
        'This branch has strong basket value and high operating quality.',
        'The opportunity is scaling visibility around the right demand moments.',
        'We want to grow demand without weakening the current premium position.',
      ],
      watchout: 'Over-discounting could damage the premium value proposition that is driving the current AOV.',
    },
  },
  {
    vendorId: 100239,
    mainChefId: 1094,
    city: 'Jeddah',
    cuisine: 'Flowers & Gifts',
    storyTag: 'ops_reset',
    classification: 'Needs Attention',
    finalScore: 66.84,
    summary: 'Category demand is attractive, but branch quality is inconsistent and needs cleanup.',
    reason: 'quality inconsistency is suppressing otherwise attractive category demand',
    actionHint: 'Fix operating reliability first, then scale gifting demand.',
    kpis: {
      deliveredOrdersRecent: 62,
      deliveredOrdersPrev: 59,
      ordersTrendPct: 5.08,
      deliveredGmvRecent: 10188.4,
      deliveredGmvPrev: 9742.9,
      gmvTrendPct: 4.57,
      avgOrderValueRecent: 164.33,
      deliveredRateRecent: 0.891,
      declineRateRecent: 0.034,
      cancelRateRecent: 0.075,
      freeDeliveryRateRecent: 0.071,
      subsidyRatioRecent: 0.0081,
      netTakeRatioRecent: 0.1676,
    },
    scores: {
      growth: 58,
      quality: 60,
      efficiency: 79,
      seasonality: 69,
      benchmark: 65,
    },
    benchmarks: {
      ordersPercentile: 46,
      gmvPercentile: 51,
      aovPercentile: 90,
      qualityPercentile: 49,
      efficiencyPercentile: 77,
    },
    copilot: {
      performanceSummary: 'The commercial model is not the main problem here. The branch still serves an attractive category, but inconsistent quality is limiting how much demand it can convert and retain.',
      likelyCauses: [
        'Order preparation or fulfillment reliability may be inconsistent.',
        'The branch may be missing demand because operational quality varies too much.',
        'High basket value means poor experiences could be especially costly.',
      ],
      actions: [
        'Diagnose why the branch is producing weaker quality than sister branches.',
        'Stabilize the operating model before trying to drive more traffic.',
        'Review staffing, acceptance behavior, and peak execution.',
      ],
      talkingPoints: [
        'The category opportunity is real, but branch quality is holding performance back.',
        'We need to make the experience more reliable before scaling demand.',
        'Once branch quality is stable, the commercial upside should be easier to unlock.',
      ],
      watchout: 'Poor experiences in a premium gifting category can damage repeat demand disproportionately.',
    },
  },
  {
    vendorId: 100286,
    mainChefId: 1118,
    city: 'Medina',
    cuisine: 'Groceries',
    storyTag: 'weekend_warrior',
    classification: 'Healthy',
    finalScore: 70.86,
    summary: 'Healthy demand and perfect seasonality fit, but subsidy and free-delivery usage should be tightened.',
    reason: 'positive recent growth; healthy subsidy efficiency',
    actionHint: 'Maintain momentum: protect service quality, keep efficient support, and test small growth levers.',
    kpis: {
      deliveredOrdersRecent: 98,
      deliveredOrdersPrev: 82,
      ordersTrendPct: 19.51,
      deliveredGmvRecent: 11140.12,
      deliveredGmvPrev: 9297.55,
      gmvTrendPct: 19.85,
      avgOrderValueRecent: 113.67,
      deliveredRateRecent: 0.8991,
      declineRateRecent: 0.0275,
      cancelRateRecent: 0.0734,
      freeDeliveryRateRecent: 0.1651,
      subsidyRatioRecent: 0.0243,
      netTakeRatioRecent: 0.1668,
    },
    scores: {
      growth: 80,
      quality: 71,
      efficiency: 63,
      seasonality: 100,
      benchmark: 58,
    },
    benchmarks: {
      ordersPercentile: 41,
      gmvPercentile: 46,
      aovPercentile: 67,
      qualityPercentile: 68,
      efficiencyPercentile: 52,
    },
    copilot: {
      performanceSummary: 'This vendor is performing well enough to be considered healthy, but the support model needs monitoring. Demand is present and seasonality fit is strong, yet the branch may be leaning too much on free-delivery support to maintain momentum.',
      likelyCauses: [
        'Demand is real, but some conversion may be artificially supported by delivery incentives.',
        'Seasonality is helping the branch, which may mask underlying efficiency leakage.',
        'The branch may benefit from tighter promo strategy rather than blanket support.',
      ],
      actions: [
        'Audit the free-delivery setup and reduce low-return support.',
        'Shift from broad subsidy to selective promo windows or targeted items.',
        'Measure whether order retention holds after tightening support.',
      ],
      talkingPoints: [
        'Performance is healthy, but we see room to improve efficiency.',
        'We want to preserve growth while making support more targeted.',
        'The goal is better profitability, not less demand.',
      ],
      watchout: 'Removing support too abruptly could distort short-term performance, so changes should be staged.',
    },
  },
  {
    vendorId: 100291,
    mainChefId: 1118,
    city: 'Medina',
    cuisine: 'Groceries',
    storyTag: 'margin_guard',
    classification: 'Needs Attention',
    finalScore: 64.73,
    summary: 'The branch is holding demand, but discounts and support are likely eating too much value.',
    reason: 'support intensity is too high relative to branch growth and quality',
    actionHint: 'Tighten branch-level support and protect profitability before scaling further.',
    kpis: {
      deliveredOrdersRecent: 104,
      deliveredOrdersPrev: 95,
      ordersTrendPct: 9.47,
      deliveredGmvRecent: 10976.5,
      deliveredGmvPrev: 10202.8,
      gmvTrendPct: 7.58,
      avgOrderValueRecent: 105.54,
      deliveredRateRecent: 0.892,
      declineRateRecent: 0.026,
      cancelRateRecent: 0.082,
      freeDeliveryRateRecent: 0.214,
      subsidyRatioRecent: 0.0318,
      netTakeRatioRecent: 0.1614,
    },
    scores: {
      growth: 61,
      quality: 67,
      efficiency: 45,
      seasonality: 89,
      benchmark: 62,
    },
    benchmarks: {
      ordersPercentile: 44,
      gmvPercentile: 43,
      aovPercentile: 55,
      qualityPercentile: 61,
      efficiencyPercentile: 34,
    },
    copilot: {
      performanceSummary: 'This branch is not collapsing operationally, but the economics are under pressure. Support appears heavy relative to the amount of branch growth it is producing.',
      likelyCauses: [
        'Free delivery and subsidy are likely carrying too much of the conversion burden.',
        'The branch may not be retaining enough profitable demand without support.',
        'Some of the current momentum may not be efficient to sustain.',
      ],
      actions: [
        'Reduce broad support and move to tighter branch-level campaigns.',
        'Test which branch baskets retain demand after support is reduced.',
        'Monitor profitability signals alongside volume.',
      ],
      talkingPoints: [
        'The branch has demand, but the current support model may be too expensive.',
        'We want to preserve the right demand, not subsidize everything equally.',
        'A tighter branch strategy should improve quality of growth.',
      ],
      watchout: 'If support is cut without sequencing, the branch could show a sudden but misleading drop in volume.',
    },
  },
  {
    vendorId: 100295,
    mainChefId: 1118,
    city: 'Yanbu',
    cuisine: 'Groceries',
    storyTag: 'emerging_city',
    classification: 'High Potential',
    finalScore: 73.94,
    summary: 'A smaller branch with promising operating quality and meaningful upside in a lighter market.',
    reason: 'good branch quality with room to grow in an emerging city',
    actionHint: 'Scale carefully through visibility and demand capture, not through aggressive support.',
    kpis: {
      deliveredOrdersRecent: 77,
      deliveredOrdersPrev: 63,
      ordersTrendPct: 22.22,
      deliveredGmvRecent: 8640.3,
      deliveredGmvPrev: 7002.1,
      gmvTrendPct: 23.39,
      avgOrderValueRecent: 112.21,
      deliveredRateRecent: 0.931,
      declineRateRecent: 0.022,
      cancelRateRecent: 0.047,
      freeDeliveryRateRecent: 0.097,
      subsidyRatioRecent: 0.0117,
      netTakeRatioRecent: 0.1695,
    },
    scores: {
      growth: 79,
      quality: 81,
      efficiency: 84,
      seasonality: 79,
      benchmark: 63,
    },
    benchmarks: {
      ordersPercentile: 39,
      gmvPercentile: 37,
      aovPercentile: 64,
      qualityPercentile: 80,
      efficiencyPercentile: 76,
    },
    copilot: {
      performanceSummary: 'This branch is still smaller than the main city branches, but the quality profile is healthy and the branch appears capable of scaling with the right demand capture strategy.',
      likelyCauses: [
        'The branch likely serves a smaller but still underdeveloped demand pocket.',
        'Good service quality creates a foundation for efficient scaling.',
        'Branch growth should come from capture and awareness more than promotion depth.',
      ],
      actions: [
        'Increase visibility in the best branch demand windows.',
        'Prioritize strong repeat items over broad subsidized traffic.',
        'Use the branch as a measured scale-up test in the city.',
      ],
      talkingPoints: [
        'This branch looks operationally healthy and ready for controlled growth.',
        'We should scale with precision, not with blanket discounting.',
        'The upside is building a stronger demand base in the city over time.',
      ],
      watchout: 'Small branches can be more volatile, so demand tests should stay measured.',
    },
  },
  {
    vendorId: 100004,
    mainChefId: 1001,
    city: 'Jeddah',
    cuisine: 'Sweets',
    storyTag: 'weekend_warrior',
    classification: 'At Risk',
    finalScore: 79.14,
    summary: 'Strong demand and growth, but elevated cancellations create a real operational risk.',
    reason: 'high cancel rate',
    actionHint: 'Prioritize intervention: review decline/cancel drivers, reduce weak subsidy spend, and fix fulfillment quality.',
    kpis: {
      deliveredOrdersRecent: 260,
      deliveredOrdersPrev: 209,
      ordersTrendPct: 24.4,
      deliveredGmvRecent: 19078.57,
      deliveredGmvPrev: 14938.96,
      gmvTrendPct: 27.71,
      avgOrderValueRecent: 73.38,
      deliveredRateRecent: 0.8844,
      declineRateRecent: 0.0204,
      cancelRateRecent: 0.0952,
      freeDeliveryRateRecent: 0.1361,
      subsidyRatioRecent: 0.0168,
      netTakeRatioRecent: 0.1691,
    },
    scores: {
      growth: 96.33,
      quality: 58.95,
      efficiency: 88.23,
      seasonality: 98.61,
      benchmark: 62.05,
    },
    benchmarks: {
      ordersPercentile: 61.81,
      gmvPercentile: 70.83,
      aovPercentile: 52.78,
      qualityPercentile: 47.92,
      efficiencyPercentile: 61.11,
    },
    copilot: {
      performanceSummary: 'This branch is showing strong demand and good seasonality fit, but it is classified as At Risk because operational quality is beginning to break under that demand. Elevated cancellations are the key warning signal.',
      likelyCauses: [
        'Demand growth may be outpacing fulfillment reliability.',
        'Operational strain during peak or weekend-heavy periods may be driving cancellations.',
        'The business may be scaling faster than the branch can currently execute.',
      ],
      actions: [
        'Investigate the operational reason for the elevated cancellations immediately.',
        'Avoid adding more traffic or subsidy until fulfillment quality stabilizes.',
        'Review peak-hour readiness, menu complexity, and merchant acceptance behavior.',
      ],
      talkingPoints: [
        'Demand is strong, which is positive, but cancellations are now a serious operational risk.',
        'Fixing fulfillment quality will protect growth better than adding more visibility right now.',
        'Once operational stability improves, we can scale confidently.',
      ],
      watchout: 'If the branch keeps growing without fixing cancellations, customer experience and repeat demand may deteriorate.',
    },
  },
  {
    vendorId: 100006,
    mainChefId: 1001,
    city: 'Jeddah',
    cuisine: 'Sweets',
    storyTag: 'stable_core',
    classification: 'Healthy',
    finalScore: 82.33,
    summary: 'This sister branch is healthier, showing that the brand can scale well when operations stay under control.',
    reason: 'good branch growth with stable quality and efficient support',
    actionHint: 'Use this branch as the operating reference point for the weaker branches.',
    kpis: {
      deliveredOrdersRecent: 221,
      deliveredOrdersPrev: 187,
      ordersTrendPct: 18.18,
      deliveredGmvRecent: 17110.6,
      deliveredGmvPrev: 14454.2,
      gmvTrendPct: 18.38,
      avgOrderValueRecent: 77.42,
      deliveredRateRecent: 0.938,
      declineRateRecent: 0.018,
      cancelRateRecent: 0.033,
      freeDeliveryRateRecent: 0.094,
      subsidyRatioRecent: 0.0104,
      netTakeRatioRecent: 0.1703,
    },
    scores: {
      growth: 84,
      quality: 86,
      efficiency: 90,
      seasonality: 91,
      benchmark: 77,
    },
    benchmarks: {
      ordersPercentile: 58,
      gmvPercentile: 64,
      aovPercentile: 55,
      qualityPercentile: 86,
      efficiencyPercentile: 83,
    },
    copilot: {
      performanceSummary: 'This branch proves the brand can grow without sacrificing quality. It is a useful internal benchmark for what good branch execution should look like.',
      likelyCauses: [
        'Branch execution is more stable than the riskier sister branch.',
        'Support appears more disciplined and less distortionary.',
        'The branch may be better prepared for peak demand windows.',
      ],
      actions: [
        'Identify which operating practices this branch is getting right.',
        'Use this branch as a reference model for weaker branches.',
        'Protect current quality while scaling demand gradually.',
      ],
      talkingPoints: [
        'This branch shows the brand can scale in a healthy way.',
        'The opportunity is to replicate this operating model elsewhere.',
        'We should learn from the stronger branch before adding more pressure to weaker ones.',
      ],
      watchout: 'Do not assume all branches can absorb growth in the same way without branch-specific checks.',
    },
  },
  {
    vendorId: 100011,
    mainChefId: 1001,
    city: 'Mecca',
    cuisine: 'Sweets',
    storyTag: 'seasonal_burst',
    classification: 'High Potential',
    finalScore: 75.08,
    summary: 'Strong demand moments are visible, but the branch is still under-scaled compared with its seasonal opportunity.',
    reason: 'good demand moments and acceptable quality, but branch is not yet fully scaled',
    actionHint: 'Scale around peak demand periods with tighter planning and exposure.',
    kpis: {
      deliveredOrdersRecent: 173,
      deliveredOrdersPrev: 138,
      ordersTrendPct: 25.36,
      deliveredGmvRecent: 12921.8,
      deliveredGmvPrev: 10387.4,
      gmvTrendPct: 24.4,
      avgOrderValueRecent: 74.69,
      deliveredRateRecent: 0.917,
      declineRateRecent: 0.023,
      cancelRateRecent: 0.051,
      freeDeliveryRateRecent: 0.104,
      subsidyRatioRecent: 0.0123,
      netTakeRatioRecent: 0.1696,
    },
    scores: {
      growth: 83,
      quality: 76,
      efficiency: 84,
      seasonality: 94,
      benchmark: 68,
    },
    benchmarks: {
      ordersPercentile: 49,
      gmvPercentile: 55,
      aovPercentile: 53,
      qualityPercentile: 73,
      efficiencyPercentile: 75,
    },
    copilot: {
      performanceSummary: 'This branch shows strong seasonal upside and acceptable operating quality. It looks like a branch that can grow meaningfully if peak demand is captured more deliberately.',
      likelyCauses: [
        'Seasonal demand windows are creating visible upside.',
        'The branch likely has room to scale if planning improves around those peaks.',
        'Current support levels are not the main problem, execution and capture are.',
      ],
      actions: [
        'Strengthen readiness around the most important branch demand periods.',
        'Increase branch exposure only when operationally prepared.',
        'Review whether top-performing SKUs are visible enough during peak moments.',
      ],
      talkingPoints: [
        'This branch has real upside if we capture the strongest demand windows better.',
        'The goal is scaling with readiness, not just pushing more traffic.',
        'We should align branch operations and visibility around those moments.',
      ],
      watchout: 'If demand spikes are not managed operationally, the branch could quickly move from potential to risk.',
    },
  },
]

export function classificationTone(classification: VendorCase['classification']): DemoTone {
  if (classification === 'Healthy') return 'good'
  if (classification === 'High Potential') return 'info'
  if (classification === 'At Risk') return 'critical'
  return 'warn'
}
